### ISSUE TITLE
Show in rest, default to true

### ISSUE THREAD

**Issue by Art2B** [WebDevStudios/custom-post-type-ui#537] opened 2016-08-18 09:24 UTC
Hello,

I have a question about the default value of `show_in_rest`. It's actually to `false`, and I would like it to be default to `true` without having to modify the plugins (principaly to allow me to deploy the site I build on multiple platform without having to update your plugin by hand each time). 

So I would like to know if I can change the default value in my themes files ?

Thanks,
Arthur

**Comment by tw2113** [comment] 2016-08-18 14:39
I'd consider using the filter at the following spot: https://github.com/WebDevStudios/custom-post-type-ui/blob/alpha/custom-post-type-ui.php#L435-L445

You could set up a callback on it for all post types registered through our plugin and set show_in_rest to true if no option is chosen for it, which should be found/not found in the `$post_type` param passed in.

**Comment by tw2113** [comment] 2016-08-18 14:40
Closing as it's not a bug/feature enhancement. You can still comment even if closed.

**Closed by tw2113** 2016-08-18 14:40 UTC
Labels: wontfix

**Comment by Art2B** [comment] 2016-08-18 15:37
Thanks, it worked :)

**Comment by tw2113** [comment] 2016-08-18 15:40
Awesome.
