### ISSUE TITLE
how to update taxonomy of a product programtically from my custom  plugin

### ISSUE THREAD

**Issue by pratikraman-dev** [WebDevStudios/custom-post-type-ui#817] opened 2021-08-25 06:30 UTC

**Comment by tw2113** [comment] 2021-08-25 14:22
@pratikraman-dev if you're talking about changing associated terms and whatnot on a given post, of any post type, you could use https://developer.wordpress.org/reference/functions/wp_set_object_terms/

Closing the issue as it's not a bug or anything, but I can continue answering potential questions.

**Closed by tw2113** 2021-08-25 14:22 UTC
